export const countries = [
  { code: "AU", name: "Australia", flag: "🇦🇺", base_delivery_npr: 1905 },
  { code: "AT", name: "Austria", flag: "🇦🇹", base_delivery_npr: 1870 },
  { code: "BE", name: "Belgium", flag: "🇧🇪", base_delivery_npr: 2375 },
  { code: "DK", name: "Denmark", flag: "🇩🇰", base_delivery_npr: 1770 },
  { code: "FI", name: "Finland", flag: "🇫🇮", base_delivery_npr: 2295 },
  { code: "FR", name: "France", flag: "🇫🇷", base_delivery_npr: 1925 },
  { code: "DE", name: "Germany", flag: "🇩🇪", base_delivery_npr: 2315 },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", base_delivery_npr: 1585 },
  { code: "IT", name: "Italy", flag: "🇮🇹", base_delivery_npr: 1725 },
  { code: "IN", name: "India", flag: "🇮🇳", base_delivery_npr: 1350 },
  { code: "JP", name: "Japan", flag: "🇯🇵", base_delivery_npr: 1455 },
  { code: "KR", name: "South Korea", flag: "🇰🇷", base_delivery_npr: 1695 },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", base_delivery_npr: 1220 },
  { code: "MV", name: "Maldives", flag: "🇲🇻", base_delivery_npr: 1210 },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", base_delivery_npr: 1720 },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", base_delivery_npr: 2440 },
  { code: "NP", name: "Nepal", flag: "🇳🇵", base_delivery_npr: 100 },
  { code: "NO", name: "Norway", flag: "🇳🇴", base_delivery_npr: 2410 },
  { code: "PH", name: "Philippines", flag: "🇵🇭", base_delivery_npr: 1105 },
  { code: "QA", name: "Qatar", flag: "🇶🇦", base_delivery_npr: 1060 },
  { code: "SG", name: "Singapore", flag: "🇸🇬", base_delivery_npr: 1210 },
  { code: "ES", name: "Spain", flag: "🇪🇸", base_delivery_npr: 1920 },
  { code: "SE", name: "Sweden", flag: "🇸🇪", base_delivery_npr: 2135 },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", base_delivery_npr: 1670 },
  { code: "TH", name: "Thailand", flag: "🇹🇭", base_delivery_npr: 1065 },
  { code: "AE", name: "UAE", flag: "🇦🇪", base_delivery_npr: 1000 },
  { code: "GB", name: "UK", flag: "🇬🇧", base_delivery_npr: 2450 },
  { code: "US", name: "USA", flag: "🇺🇸", base_delivery_npr: 2200 },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", base_delivery_npr: 1100 },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", base_delivery_npr: 1180 },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", base_delivery_npr: 1715 },
  { code: "CN", name: "China", flag: "🇨🇳", base_delivery_npr: 1585 },
  { code: "MO", name: "Macao", flag: "🇲🇴", base_delivery_npr: 1660 },
  { code: "TR", name: "Turkey", flag: "🇹🇷", base_delivery_npr: 1925 },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", base_delivery_npr: 1020 },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", base_delivery_npr: 795 },
];
