export const cities = [
  { sn: "1", name: "Biratnagar" },
  { sn: "2", name: "Lahan" },
  { sn: "4", name: "Damak" },
  { sn: "5", name: "Birtamod" },
  { sn: "7", name: "Bhadrapur" },
  { sn: "8", name: "Surunga" },
  { sn: "10", name: "Budhabare" },
  { sn: "15", name: "Uralabari" },
  { sn: "16", name: "Pathari" },
  { sn: "21", name: "Belbari" },
  { sn: "32", name: "Itahari" },
  { sn: "33", name: "Dharan" },
  { sn: "34", name: "Inaruwa" },
  { sn: "35", name: "Duhabi" },
  { sn: "69", name: "Banepa" },
  { sn: "70", name: "Dhulikhel" },
  { sn: "71", name: "Panauti" },
  { sn: "144", name: "Bharatpur" },
  { sn: "146", name: "Tandi" },
  { sn: "170", name: "Surkhet" },
  { sn: "172", name: "Pokhara" },
  { sn: "173", name: "Kathmandu" },
  { sn: "176", name: "Butwal" },
  { sn: "178", name: "Birgunj" },
  { sn: "179", name: "Janakpur" },
  { sn: "181", name: "Bardibas" },
  { sn: "183", name: "Bhairahawa" },
  { sn: "185", name: "Nepalgunj" },
  { sn: "186", name: "Dhangadhi" },
  { sn: "187", name: "Ghorahi" },
  { sn: "188", name: "Biratchowk" },
  { sn: "189", name: "Rajbiraj" },
  { sn: "192", name: "Tikapur" },
  { sn: "193", name: "Lamki" },
  { sn: "194", name: "Bauniya" },
  { sn: "195", name: "Tulsipur" },
  { sn: "196", name: "Damauli" },
  { sn: "199", name: "Bardaghat" },
  { sn: "200", name: "Kawasoti" },
  { sn: "202", name: "Kohalpur" },
  { sn: "203", name: "Dumre" },
  { sn: "205", name: "Kusma" },
  { sn: "206", name: "Beni" },
  { sn: "275", name: "Baglung" },
  { sn: "289", name: "Mahendranagar Dhanusa" },
  { sn: "308", name: "Dhungeadda" },
  { sn: "312", name: "Kalaiya" },
  { sn: "317", name: "Simara" },
  { sn: "322", name: "Tansen" },
  { sn: "324", name: "Lamahi" },
  { sn: "329", name: "Rangeli" },
  { sn: "333", name: "Hetauda" },
  { sn: "334", name: "Attariya" },
  { sn: "335", name: "Inside Ringroad" },
  { sn: "336", name: "Outside Ringroad" },
  { sn: "337", name: "Narayangarh" },
  { sn: "339", name: "Kakarbhitta" },
  { sn: "340", name: "Dhulabari" },
  { sn: "341", name: "Gulariya" },
  { sn: "344", name: "Tinkune" },
  { sn: "345", name: "Tia Airport" },
  { sn: "346", name: "Sinamangal" },
  { sn: "347", name: "Gaushala" },
  { sn: "348", name: "Mitra Park" },
  { sn: "349", name: "Chabahil" },
  { sn: "350", name: "Sukedhara" },
  { sn: "351", name: "Dhumbarahi" },
  { sn: "352", name: "Chapalkarkhana" },
  { sn: "353", name: "Maharajgunj" },
  { sn: "354", name: "Basundhara" },
  { sn: "355", name: "Samakhusi" },
  { sn: "356", name: "Gongabu" },
  { sn: "357", name: "Machapokhari" },
  { sn: "358", name: "Balaju" },
  { sn: "359", name: "Banasthali" },
  { sn: "360", name: "Thulobharyang" },
  { sn: "361", name: "Sanobharyang" },
  { sn: "362", name: "Swyambhu" },
  { sn: "363", name: "Sitapaila" },
  { sn: "364", name: "Chauni" },
  { sn: "365", name: "Kalanki" },
  { sn: "366", name: "Balkhu" },
  { sn: "367", name: "Sanepa" },
  { sn: "368", name: "Dhobighat" },
  { sn: "369", name: "Ekantakuna" },
  { sn: "370", name: "Mahalaxmisthan" },
  { sn: "371", name: "Kusunti" },
  { sn: "372", name: "Thasikhel" },
  { sn: "373", name: "Satdobato" },
  { sn: "374", name: "Gwarko" },
  { sn: "375", name: "Balkumari" },
  { sn: "376", name: "Koteshwor" },
  { sn: "377", name: "Jadibuti" },
  { sn: "378", name: "Lokanthali" },
  { sn: "379", name: "Kausaltar" },
  { sn: "380", name: "Ghattaghar" },
  { sn: "381", name: "Nayathimi" },
  { sn: "382", name: "Radhe Radhe" },
  { sn: "383", name: "Sallaghari" },
  { sn: "384", name: "Suryabinayak" },
  { sn: "385", name: "Jagati" },
  { sn: "386", name: "Kamalbinayak" },
  { sn: "387", name: "Bhaktapur Durbar Square" },
  { sn: "388", name: "Bode" },
  { sn: "389", name: "Purano Thimi" },
  { sn: "390", name: "Pepsicola" },
  { sn: "391", name: "Kadaghari" },
  { sn: "392", name: "Mulpani" },
  { sn: "393", name: "Thali" },
  { sn: "394", name: "Jorpati" },
  { sn: "395", name: "Baudha" },
  { sn: "396", name: "Chucchepati" },
  { sn: "397", name: "Kapan" },
  { sn: "398", name: "Budanilkantha" },
  { sn: "399", name: "Bansbari" },
  { sn: "400", name: "Naikap" },
  { sn: "401", name: "Satungal" },
  { sn: "403", name: "Kiritipur" },
  { sn: "404", name: "Bhaisipati" },
  { sn: "405", name: "Khumaltar" },
  { sn: "406", name: "Chapagaun" },
  { sn: "408", name: "Dhapakhel" },
  { sn: "410", name: "Hattiban" },
  { sn: "411", name: "Tikathali" },
  { sn: "413", name: "New Baneshwor" },
  { sn: "414", name: "Old Baneshwor" },
  { sn: "415", name: "Battisputali" },
  { sn: "416", name: "Thapagaun" },
  { sn: "417", name: "Anamnagar" },
  { sn: "418", name: "Ghattekulo" },
  { sn: "419", name: "Putalisadak" },
  { sn: "420", name: "Bagbazar" },
  { sn: "421", name: "Kamaladi" },
  { sn: "422", name: "Hattisar" },
  { sn: "423", name: "Nagpokhari" },
  { sn: "424", name: "Durbarmarg" },
  { sn: "425", name: "Ratnapark" },
  { sn: "426", name: "Sundhara" },
  { sn: "427", name: "Newroad" },
  { sn: "428", name: "Basantapur" },
  { sn: "429", name: "Chetrapati" },
  { sn: "430", name: "Dallu" },
  { sn: "431", name: "Kalimati" },
  { sn: "432", name: "Soltimode" },
  { sn: "433", name: "Teku" },
  { sn: "434", name: "Tripureshwor" },
  { sn: "435", name: "Sorakhutte" },
  { sn: "436", name: "Lazimpat" },
  { sn: "437", name: "Panipokhari" },
  { sn: "438", name: "Naxal" },
  { sn: "439", name: "Baluwatar" },
  { sn: "440", name: "Kalopul" },
  { sn: "441", name: "Nayabazar" },
  { sn: "442", name: "Maipi" },
  { sn: "443", name: "Kupandol" },
  { sn: "444", name: "Patan" },
  { sn: "445", name: "Lagankhel" },
  { sn: "446", name: "Jawalakhel" },
  { sn: "447", name: "Parasi" },
  { sn: "448", name: "Thamel" },
  { sn: "450", name: "Sukkhad" },
  { sn: "452", name: "Jeetpur Bara" },
  { sn: "453", name: "Syangja Galyang" },
  { sn: "454", name: "Charaali" },
  { sn: "455", name: "Gaidakot" },
  { sn: "457", name: "Tokha" },
  { sn: "465", name: "Baniyatar" },
  { sn: "466", name: "Imadol" },
  { sn: "467", name: "Santinagar" },
  { sn: "468", name: "Aanbu Khaireni Tanahu" },
  { sn: "469", name: "Gaighat" },
  { sn: "471", name: "Chandrauta" },
  { sn: "473", name: "Besi Sahar" },
  { sn: "474", name: "Dailekh Bazar" },
  { sn: "475", name: "Diktel Khotang" },
  { sn: "476", name: "Amargadhi" },
  { sn: "478", name: "Fikkal" },
  { sn: "479", name: "Phidim" },
  { sn: "480", name: "Chandranigahapur" },
  { sn: "482", name: "Phattepur" },
  { sn: "483", name: "Kanchanpur Saptari" },
  { sn: "484", name: "Dipayal Bazar" },
];
