const productDescription = `{"type":"doc","content":[{"type":"heading","attrs":{"textAlign":null,"level":3},"content":[{"type":"text","text":"🍪 "},{"type":"text","marks":[{"type":"bold"}],"text":"Arksh Food Dami Biscuit (Kodo/Millet)"}]},{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🌾 Healthy meets tasty! 🌾"},{"type":"hardBreak"},{"type":"text","text":"The "},{"type":"text","marks":[{"type":"bold"}],"text":"Dami Biscuit"},{"type":"text","text":" is made from "},{"type":"text","marks":[{"type":"bold"}],"text":"Kodo/Millet"},{"type":"text","text":", giving you a crunchy, wholesome snack that’s both nutritious and delicious 💪. Light, guilt-free, and perfect for anytime munching – from office desk 🖥️ to evening tea ☕. Packed with fiber and flavor, this is the smart snacker’s choice! 😋✨"}]}]}`

const productIngredients = `{"type":"doc","content":[{"type":"heading","attrs":{"textAlign":null,"level":3},"content":[{"type":"text","text":"🥖 "},{"type":"text","marks":[{"type":"bold"}],"text":"Ingredients"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🌾 Kodo / Millet Flour"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🧈 Pure Butter"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🍬 Natural Sugar"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🥛 Fresh Milk"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🧂 Pinch of Salt"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"⚡ Baking Powder"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"✨ Touch of Vanilla"}]}]}]},{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","marks":[{"type":"italic"}],"text":"(Extra love baked into every bite ❤️)"}]}]}`

const productOrderDetails = `{"type":"doc","content":[{"type":"heading","attrs":{"textAlign":null,"level":3},"content":[{"type":"text","text":"📦 "},{"type":"text","marks":[{"type":"bold"}],"text":"Order Details"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🏷 "},{"type":"text","marks":[{"type":"bold"}],"text":"Name:"},{"type":"text","text":" Arksh Food Dami Biscuit (Kodo/Millet)"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"⚖️ "},{"type":"text","marks":[{"type":"bold"}],"text":"Weight:"},{"type":"text","text":" 50gm per pack"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🔢 "},{"type":"text","marks":[{"type":"bold"}],"text":"Packs:"},{"type":"text","text":" 12 Packets (bundle for your snack stash 🎉)"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"📦 "},{"type":"text","marks":[{"type":"bold"}],"text":"Packaging:"},{"type":"text","text":" Fresh-lock pouches in an eco-friendly box 🌍💚"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🕒 "},{"type":"text","marks":[{"type":"bold"}],"text":"Shelf Life:"},{"type":"text","text":" Up to 20 days in a cool, dry place"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"🚚 "},{"type":"text","marks":[{"type":"bold"}],"text":"Delivery:"},{"type":"text","text":" 2–4 business days"}]}]},{"type":"listItem","content":[{"type":"paragraph","attrs":{"textAlign":null},"content":[{"type":"text","text":"⭐ "},{"type":"text","marks":[{"type":"bold"}],"text":"Special Note:"},{"type":"text","text":" Perfect for health-conscious snack lovers 🥗"}]}]}]}]}`

export const productSeedConstants = {
    productDescription,
    productIngredients,
    productOrderDetails
}
